pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		gradlePluginPortal()
		mavenLocal()
	}
}

if (!JavaVersion.current().isCompatibleWith(JavaVersion.VERSION_17)) {
	throw new UnsupportedOperationException("Yarn's buildscript requires Java 17 or higher.")
}

rootProject.name = "b1.7.3-mojmaps"